testandoBancodDo0/Controllers/ReceitasApiController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Policy;
using testandoBancodDo0.ApiServices;

namespace testandoBancodDo0.Controllers
{
    public class ReceitasApiController : Controller
    {
        private readonly ReceitasServices _receitasServices;

        public ReceitasApiController(ReceitasServices receitasServices)
        {
            _receitasServices = receitasServices;
        }
        public async Task<IActionResult> IndexReceitas()
        {
            var receitas = await _receitasServices.GetReceitasAsync();
            var usuarioAutenticado = HttpContext.Session.GetString("UserId");
            if (usuarioAutenticado == null)
            {
                return View("~/Views/Site/PrincipalHome.cshtml", receitas);
            }
            return View("~/Views/Site/PrincipalHomeAutenticado.cshtml", receitas);
            
        }

        public async Task<IActionResult> Details (int id)
        {
            var receita = await _receitasServices.GetReceitasByIdAsync(id);
            if (receita is null) return null!;
            return View("~/Views/Receitas/DetalhesReceitas.cshtml", receita);
        }
    }
}

testandoBancodDo0/Controllers/ReceitasController.cs
using Microsoft.AspNetCore.Mvc;

namespace testandoBancodDo0.Controllers
{
    public class ReceitasController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ReceitaAbobora()
        {
            return View();
        }

        public IActionResult ReceitaFrango()
        {
            return View();
        }

        public IActionResult ReceitaGaspacho()
        {
            return View();
        }

        public IActionResult ReceitaHotDog()
        {
            return View();
        }

        public IActionResult ReceitaMacarronada()
        {
            return View();
        }

        public IActionResult ReceitaRocambole()
        {
            return View();
        }
    }
}

testandoBancodDo0/Controllers/SiteController.cs
using Microsoft.AspNetCore.Mvc;

namespace testandoBancodDo0.Controllers
{
    public class SiteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Cadastro()
        {
            return View();
        }

        public IActionResult Contato()
        {
            return View();
        }

        public IActionResult Favoritos()
        {
            return View();
        }

        public IActionResult CadastrarReceita()
        {
            return View();
        }

        public IActionResult TelaAdm()
        {
            return View();
        }

        public IActionResult ExibirSenha()
        {
            return View();
        }

        public IActionResult AreaUsuario()
        {
            return View();
        }

        public IActionResult CadastraReceita()
        {
            return View();
        }

        public IActionResult SobreNos()
        {
            return View();
        }

        public IActionResult PrincipalHome()
        {
            return View();
        }

        public IActionResult PrincipalHomeAutenticado()
        {
            return View();
        }

    }
}

testandoBancodDo0/Views/Receitas/DetalhesReceitas.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model testandoBancodDo0.Models.ReceitasModel
<!doctype html>
<html lang="pt-br">
<head>
    <script src="https://kit.fontawesome.com/6f925b0522.js" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@Model?.Nome</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/Receitas.css">
    <link rel="icon" type="image/ico" href="~/css/logo.ico">
</head>
<body>
    <!-- topo-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top navbar-custom" style="background-color: #091B26;">
        <a class="navbar-brand" asp-controller="ReceitasApi" asp-action="IndexReceitas"><span style="color: #FE9900;">Aprove</span> Receitas</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="ReceitasApi" asp-action="IndexReceitas">Inicio <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Site" asp-action="Favoritos">Favoritos</a>
                </li>
                <!--<li class="nav-item">
                    <a class="nav-link" asp-controller="Site" asp-action="PrincipalHome">Receitas</a>
                </li>-->
            </ul>
            <div class="UsuarioLogado">
                @if (Context.Session.GetString("UserId") != null)
                {
                    <a asp-controller="Site" asp-action="AreaUsuario">
                        <span style="color:white; font-size:22px;">Olá, @Context.Session.GetString("UserName")!</span>
                    </a>
                }
            </div>
        </div>
    </nav>
    <!--para telas menores-->
    <div id="home" class="container-fluid">
    </div>

    <div id="about" class="container-fluid">
    </div>

    <div id="services" class="container-fluid">
    </div>
    <div class="separador"></div>
    <!--BODY-->

    <h1 id="titulo">@Model?.Nome</h1>
    <div class="separador"></div>
    <br>
    <div class="recipe" id="recipe2">
        <div class="imageCont">
            <img src="@Model?.UrlImagem" alt="Imagem 1" class="image">
            <br>
            <i class="favorite fa-solid fa-heart" data-recipe="2"></i> <!-- Ícone de coração -->
            <i class="share fa-regular fa-share-from-square"></i>
        </div>
    </div>
    <br>
    @*             <div class="icon2">
    <i class="fa-regular fa-clock"> 30 Min</i>
    <i class="fa-solid fa-utensils "> Facil</i>
    <i class="fa-solid fa-coins "> Custo Medio</i>
    </div> *@
    <br>

    <div class="separador"></div>
    <div class="ingredientes">
        <h2>Ingredientes</h2>
        @if (Model?.Ingredientes != null && Model.Ingredientes.Any())
        {
            foreach (var instruction in Model.Ingredientes)
            {
                <p>@instruction</p>
            }
        }

    </div>

    <p class="d-inline-flex gap-1">
        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" style="background: #FE9900; border-color: #FE9900;">
            Comprar ingredientes
        </button>
    </p>
    <div class="collapse" id="collapseExample">
        <div class="card card-body" style="color: black;">
            <a href="https://mercado.carrefour.com.br/?gad_source=1&gclid=Cj0KCQiAsburBhCIARIsAExmsu6-Rzy0P0DrgtdWY-5hLWJWokGWgi8Nz0-aDTmq01r64zHEhaoLKTkaAg4-EALw_wcB">Carrefour</a>
            <a href="https://www.comper.com.br/">Comper</a>
        </div>
        <br>
    </div>
    <div class="separador"></div>
    <br>
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/imagens/prop1.jpg" class="d-block w-90 h-auto" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/imagens/prop2.jpeg" class="d-block w-90 h-500 " alt="...">
            </div>
        </div>
    </div>
    <br>
    <div class="separador"></div>
    <br>
    <div class="preparo">
        <h2>Modo de Preparo</h2>


        @Model?.Instrucoes


    </div>
    <br>
    <div class="separador"></div>
    <footer>
        <a href="#" style="color: #FE9900;"><i class="fa-brands fa-facebook"></i></a>

        <a href="#" style="color: #FE9900;"><i class="fa-brands fa-instagram"></i></a>

        <a href="https://wa.me/5567993339665?text=Ol%C3%A1%2C+tudo+bem%3F+tenho+interesse+em+contar+com+os+seus+servi%C3%A7os." style="color: #FE9900;"><i class="fa-brands fa-whatsapp"></i></a>
        <br>
        <br>
        <span style="color: #fff;">Criado por <a href="#about" style="color: #FE9900;"><i>Aprove Receitas</i></a> | © Todos os direitos reservados 2024</span>
    </footer>
    <script src="~/js/ReceitasFav.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

testandoBancodDo0/Views/Receitas/ReceitaFrango.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!doctype html>
<html lang="pt-br">
<head>
    <script src="https://kit.fontawesome.com/6f925b0522.js" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Frango Caipira</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/Receitas.css">
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon">
</head>
<body>
    <!-- topo-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top navbar-custom" style="background-color: #091B26;">
        <a class="navbar-brand" asp-controller="Site" asp-action="Home"><span style="color: #FE9900;">Aprove</span> Receitas</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Site" asp-action="Home">Inicio <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Site" asp-action="Favoritos">Favoritos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Site" asp-action="CadastrarReceita">Criar Receita</a>
                </li>
            </ul>
        </div>
    </nav>
    <!--para telas menores-->
    <div id="home" class="container-fluid">
    </div>

    <div id="about" class="container-fluid">
    </div>

    <div id="services" class="container-fluid">
    </div>
    <div class="separador"></div>
    <!--BODY-->
    <h1 id="titulo">Frango Caipira</h1>
    <div class="separador"></div>
    <br>
    <div class="recipe" id="recipe3">
        <div class="imageCont1">
            <img src="~/imagens/img-4.png" alt="Imagem 4" class="image">
            <br>
            <i class="favorite1 fa-solid fa-heart" data-recipe="3"></i> <!-- Ícone de coração -->
            <i class="share fa-regular fa-share-from-square"></i>
        </div>
    </div>
    <br>
    <div class="icon2">
        <i class="fa-regular fa-clock"> 1 Hora</i>
        <i class="fa-solid fa-utensils "> Facil</i>
        <i class="fa-solid fa-coins "> Custo Medio</i>
    </div>
    <br>
    <div class="separador"></div>
    <div class="ingredientes">
        <h2>Ingredientes</h2>
        <p>
            -1 frango caipira limpo e cortado
            <br>
            -4 dentes de alho amassados
            <br>
            -3 colheres (chá) de óleo
            <br>
            -1 maço de cheiro-verde
            <br>
            -1 cebola
            <br>
            -3 xícara de água fervente
            <br>
            -1 cebola média picadinha
            <br>
            -1 colher (chá) de açafrão
            <br>
            -1 tablete de caldo de galinha (opcional)
            <br>
            -sal e pimenta a gosto
        </p>
    </div>
    <p class="d-inline-flex gap-1">
        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" style="background: #FE9900; border-color: #FE9900;">
            Comprar ingredientes
        </button>
    </p>
    <div class="collapse" id="collapseExample">
        <div class="card card-body" style="color: black;">
            <a href="https://mercado.carrefour.com.br/?gad_source=1&gclid=Cj0KCQiAsburBhCIARIsAExmsu6-Rzy0P0DrgtdWY-5hLWJWokGWgi8Nz0-aDTmq01r64zHEhaoLKTkaAg4-EALw_wcB">Carrefour</a>
            <a href="https://www.comper.com.br/">Comper</a>
        </div>
        <br>
    </div>
    <div class="separador"></div>
    <br>
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/imagens/prop1.jpg" class="d-block w-90 h-auto" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/imagens/prop2.jpeg" class="d-block w-90 h-500 " alt="...">
            </div>
        </div>
    </div>
    <br>
    <div class="separador"></div>
    <br>
    <div class="preparo">
        <h2>Modo de Preparo</h2>
        <ul>1. Corte o frango em pedaços, tempere com o sal, o alho, a pimenta e o açafrão.</ul>
        <ul>2. Coloque o óleo em uma panela, deixe esquentar.</ul>
        <ul>3. Acomode o frango, e vá refogando aos poucos até ficar bem douradinho.</ul>
        <ul>4. Quando o frango dourar, acrescente a cebola, dê mais uma refogada até a cebola dourar. </ul>
        <ul>5. Em seguida, adicione a água e o caldo de galinha.</ul>
        <ul>6. Deixe ferver uns 20 minutos ou até o frango ficar macio, se necessário, acescente mais um pouco de água.</ul>
        <ul>7. Acrescente o cheiro-verde e sirva em seguida.</ul>
        <ul>8. Bom apetite!</ul>

    </div>
    <br>
    <div class="separador"></div>
    <footer>
        <a href="#" style="color: #FE9900;"><i class="fa-brands fa-facebook"></i></a>

        <a href="#" style="color: #FE9900;"><i class="fa-brands fa-instagram"></i></a>

        <a href="https://wa.me/5567993339665?text=Ol%C3%A1%2C+tudo+bem%3F+tenho+interesse+em+contar+com+os+seus+servi%C3%A7os." style="color: #FE9900;"><i class="fa-brands fa-whatsapp"></i></a>
        <br>
        <br>
        <span style="color: #fff;">Criado por <a href="#about" style="color: #FE9900;"><i>Aprove Receitas</i></a> | © Todos os direitos reservados 2023</span>
    </footer>
    <script src="~/js/ReceitasFav.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

testandoBancodDo0/Views/Receitas/ReceitaGaspacho.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!doctype html>
<html lang="pt-br">
<head>
    <script src="https://kit.fontawesome.com/6f925b0522.js" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Gaspacho</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/Receitas.css">
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon">
</head>
<body>
    <!-- topo-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top navbar-custom" style="background-color: #091B26;">
        <a class="navbar-brand" asp-controller="Site" asp-action="Home"><span style="color: #FE9900;">Aprove</span> Receitas</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Site" asp-action="Home">Inicio <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Site" asp-action="Favoritos">Favoritos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Site" asp-action="CadastrarReceita">Criar Receita</a>
                </li>
            </ul>
        </div>
    </nav>
    <!--para telas menores-->
    <div id="home" class="container-fluid">
    </div>

    <div id="about" class="container-fluid">
    </div>

    <div id="services" class="container-fluid">
    </div>
    <div class="separador"></div>
    <!--BODY-->
    <h1 id="titulo">Gaspacho</h1>
    <div class="separador"></div>
    <br>
    <div class="recipe" id="recipe4">
        <div class="imageCont2">
            <img src="~/imagens/img-2.png" alt="Imagem 2" class="image">
            <br>
            <i class="favorite2 fa-solid fa-heart" data-recipe="4"></i> <!-- Ícone de coração -->
            <i class="share fa-regular fa-share-from-square"></i>
        </div>
    </div>
    <br>
    <div class="icon2">
        <i class="fa-regular fa-clock"> 30 Min</i>
        <i class="fa-solid fa-utensils "> Facil</i>
        <i class="fa-solid fa-coins "> Custo Baixo</i>
    </div>
    <br>
    <div class="separador"></div>
    <div class="ingredientes">
        <h2>Ingredientes</h2>
        <p>
            -3 tomate maduros
            <br>
            -1 pimentão
            <br>
            -1 cenoura
            <br>
            -Vinagre
            <br>
            -3 copos de água fria
            <br>
            -1 pepino
            <br>
            -2 dente de alho
            <br>
            -Azeite
            <br>
            -Sal
        </p>
    </div>
    <p class="d-inline-flex gap-1">
        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" style="background: #FE9900; border-color: #FE9900;">
            Comprar ingredientes
        </button>
    </p>
    <div class="collapse" id="collapseExample">
        <div class="card card-body" style="color: black;">
            <a href="https://mercado.carrefour.com.br/?gad_source=1&gclid=Cj0KCQiAsburBhCIARIsAExmsu6-Rzy0P0DrgtdWY-5hLWJWokGWgi8Nz0-aDTmq01r64zHEhaoLKTkaAg4-EALw_wcB">Carrefour</a>
            <a href="https://www.comper.com.br/">Comper</a>
        </div>
        <br>
    </div>
    <div class="separador"></div>
    <br>
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/imagens/prop1.jpg" class="d-block w-90 h-auto" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/imagens/prop2.jpeg" class="d-block w-90 h-500 " alt="...">
            </div>
        </div>
    </div>
    <br>
    <div class="separador"></div>
    <br>
    <div class="preparo">
        <h2>Modo de Preparo</h2>
        <ul>1. Bata todos os ingredientes no liquidificador.</ul>
        <ul>2. Leve à geladeira.</ul>
        <ul>3. Sirva frio com pão.</ul>
    </div>
    <br>
    <div class="separador"></div>
    <footer>
        <a href="#" style="color: #FE9900;"><i class="fa-brands fa-facebook"></i></a>

        <a href="#" style="color: #FE9900;"><i class="fa-brands fa-instagram"></i></a>

        <a href="https://wa.me/5567993339665?text=Ol%C3%A1%2C+tudo+bem%3F+tenho+interesse+em+contar+com+os+seus+servi%C3%A7os." style="color: #FE9900;"><i class="fa-brands fa-whatsapp"></i></a>
        <br>
        <br>
        <span style="color: #fff;">Criado por <a href="#about" style="color: #FE9900;"><i>Aprove Receitas</i></a> | © Todos os direitos reservados 2023</span>
    </footer>
    <script src="~/js/ReceitasFav.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>